[package]
name = "moxin-web"
version = "0.1.0"
authors = ["Edward Tan <guofoo@gmail.com>"]
edition = "2021"
description = "Moxin Website built with Makepad"
license = "MIT OR Apache-2.0"

[dependencies]
makepad-widgets = { path = "../makepad/widgets", version = "0.6.0" }
